# Parameters for the Heart Disease project

# Data-related parameters
random_state: 42
target_column: target

# Model training parameters
model_params:
  # Will be expanded in later stages
  test_size: 0.2
  n_estimators: 100
  max_depth: 10