artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1edKKAtZy3CZLYxnm5Z0RU-tumj9a3L7I/view?usp=share_link
  local_data_file: artifacts/data_ingestion/heart_data.zip
  unzip_dir: artifacts/data_ingestion/heart_data