artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1edKKAtZy3CZLYxnm5Z0RU-tumj9a3L7I/view?usp=share_link
  local_data_file: artifacts/data_ingestion/heart_data.zip
  unzip_dir: artifacts/data_ingestion/heart_data

data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/heart_data
  status_file: artifacts/data_validation/status.txt
  required_files: ['cleveland.data', 'hungarian.data', 'switzerland.data', 'long-beach-va.data', 'processed.cleveland.data', 'processed.hungarian.data', 'processed.switzerland.data', 'processed.va.data']
  schema_file: config/schema.yaml

data_transformation:
  root_dir: artifacts/data_transformation
  data_dir: artifacts/data_ingestion/heart_data
  processed_data_dir: artifacts/data_transformation/processed
  preprocessed_file: artifacts/data_transformation/preprocessed/preprocessed.csv
  train_data_path: artifacts/data_transformation/train_test_split/train.csv
  test_data_path: artifacts/data_transformation/train_test_split/test.csv
  preprocessor_path: artifacts/data_transformation/preprocessor/preprocessor.pkl

model_trainer:
  root_dir: artifacts/model_trainer
  trained_model_path: artifacts/model_trainer/model.pkl
  metrics_path: artifacts/model_trainer/metrics.json

model_deployment:
  root_dir: artifacts/model_deployment
  trained_model_path: artifacts/model_trainer/model.pkl
  preprocessor_path: artifacts/data_transformation/preprocessor/preprocessor.pkl
  schema_file: config/schema.yaml
  prediction_pipeline_path: artifacts/model_deployment/prediction_pipeline.pkl